### ISSUE TITLE
HWID support for Windows 10 LTSC 2021 (19044)

### ISSUE THREAD

**Issue by peyman4774** [luzeadev/winactivate#16]
please support windows 10 ltsc 2021 hwid activation

**Comment by uwuowouwu420** [comment]
Sir ,
What you ask is literally impossible . Sir Mircosoft not support LTSC 2021 HIWD ! Kindly install IoT LTCS 2021 .

**Comment by win98se** [comment]
You can just run `changepk /ProductKey QPM6N-7J2WJ-P88HH-P3YRH-YY74H` under original LTSC 2021, then directly activate it using HWID. No reinstallation required.
