### ISSUE TITLE
Just a question.

### ISSUE THREAD

**Issue by DevilAccess** [luzeadev/winactivate#22]
Does WinActivate work on Windows 11 v22483 to activate HWID? because Microsoft removed wmic.exe

My best regards.

**Comment by luzeadev** [comment]
Hi, this activator was especially made for the case where `WMIC.exe` isn't present anymore.

**Comment by DevilAccess** [comment]
Hi, thank you for your answer.

Another question.

Your activator is Windows HWID/KMS38, but when a ran as administrator, there no more options, the activator activated HWID automatically. are there more activation mode options?
