### ISSUE TITLE
Settings/Update & Security not open

### ISSUE THREAD

**Issue by txdat** [luzeadev/winactivate#23]
I used your tool to active windows 10 (ver 1903, build 18362.1256). After activation, the Settings/Update & Security page doesn't open anymore (it is stuck on the Settings page), other pages can be opened normally. How can I fix it? Thank you!

**Comment by luzeadev** [comment]
Hi, I have no idea how this could be related to the activation process. Have you already tried restarting your machine?

**Comment by DevilAccess** [comment]
Hi maybe I shouldn't be here.

But this is for the user txdat.

Open PowerShell as Administrator and paste this command: Get-AppXPackage | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}

It helps to fix that kind of problems.

My best regards.

**Comment by txdat** [comment]
Thank you!
