### ISSUE TITLE
Support ARM64

### ISSUE THREAD

**Issue by ChibiANUBIS** [luzeadev/winactivate#25]
Hello my dear, Did you support ARM64 ?
I need to activate Windows 10 IoT Enterprise LTSC 2021
I can help you for testing

**Comment by luzeadev** [comment]
Hi, the script is supposed to work on ARM64 in its current state. Please try the latest release.

**Comment by ChibiANUBIS** [comment]
Ok thanks,
Because I have tested and the patching failed
![Capture](https://user-images.githubusercontent.com/71019664/147493644-81438800-d6e6-41e7-9aab-c39669a05f4b.PNG)

**Comment by ChibiANUBIS** [comment]
I switched to EnterpriseS and is ok
