### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Arashism** [luzeadev/winactivate#31]
![image](https://user-images.githubusercontent.com/99471148/153559020-67c3e472-7876-4e1f-b9dc-9037f2fd5b7f.png)

I tried Microsoft Activation Script too, Didn't help.
I activated windows with KMS around 2 months ago but after I put the PC in sleep for 8 hours, I got that activation message in bottom right.

**Comment by luzeadev** [comment]
Hi, please read the error message and do what's needed.
