### ISSUE TITLE
Work Excelent, I have just one question..

### ISSUE THREAD

**Issue by Sloba89-SRB** [luzeadev/winactivate#6]
Is there silent switch for integrating in SetupComplete.cmd? Thank you for your work.. :)

**Comment by ExeCsrss** [comment]
You can try my tool: https://github.com/ExeCsrss/EzHWID
It has the silent switch option, plus an option to generate ready-to-use $OEM$ folders

**Comment by luzeadev** [comment]
Hi, I've added the possibility to bypass the `pause` at the end by executing `winactivate.cmd` with the `/headless` flag.

**Comment by Sloba89-SRB** [comment]
Thanks

**Comment by Sloba89-SRB** [comment]
Thanks
