### ISSUE TITLE
Upgrading the Windows subscription 

### ISSUE THREAD

**Issue by filiptronicek** [luzeadev/winactivate#8]
Does this repository currently offer any way to upgrade from a licensed/unlicensed version of Windows 10/11 Home to Pro/Enterprise or does one have to setup a new Windows install?

**Comment by satyampathak223** [comment]
No I don't think so , but you can easily change editions by inserting [Generic](https://docs.microsoft.com/en-us/windows-server/get-started/kms-client-activation-keys) Pro/Enterprise Keys either through 
windows settings or through cmd.

Disconnect from internet

For windows 10 

Windows Settings  Method 
```Settings -> Update and Security -> Activation -> change Product key 
Paste the generic product key for pro/enterprise then follow on screen instructions . If you get any errors ignore it and reboot.```

Command Prompt Method
Search cmd in start menu and run it as administrator and type
```changepk.exe /ProductKey <enter your new product key here>```
or 
```Cscript.exe c:\windows\system32\slmgr.vbs /ipk <enter your new product key here>```
Ignore any errors and reboot.

Methods for windows 11 are alsosame as windows 10
