### ISSUE TITLE
LTSC 2021

### ISSUE THREAD

**Issue by pasha-zzz** [luzeadev/winactivate#9]
Hi. There is mistake in subj activation?
In ID 125 build is 19041, but final is 19044.

And only method is KMS38 (no needed key for HWID?)?

**Comment by acethical** [comment]
> Hi. There is mistake in subj activation? In ID 125 build is 19041, but final is 19044.
> 
> And only method is KMS38 (no needed key for HWID?)?

Just installed a fresh new Windows 10 Enterprise LTSC 2021, confirmed the same problem.

**Comment by uwuowouwu420** [comment]
Sirs,

LTSC 2021 does NOT support HWID activation. Do the needful and use IoT Enterprise 2021.

**Comment by pasha-zzz** [comment]
> LTSC 2021 does NOT support HWID activation.

This is secondary question. Primary is "why 19041?" W/o editing script says

`This edition or version of Windows is not supported by this script.`

**Comment by uwuowouwu420** [comment]
Sir,

Mr. Sir Developer incorrectly done the needful to assume 19044 will report 19041.

**Comment by luzeadev** [comment]
Hi, the issue was fixed in https://github.com/luzeadev/winactivate/commit/aa437f3b570032d792ed13fb8de7afd54a2468ca and will be available in the next release.
